
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mazilaa
 */
public class SelectColor extends javax.swing.JPanel {

    /**
     * Creates new form SelectColor
     */
    public SelectColor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myText1 = new MyText();
        buttonGroup1 = new javax.swing.ButtonGroup();
        myTextBlue = new MyText();
        jLabel1 = new javax.swing.JLabel();
        myTextGreen = new MyText();
        jLabel2 = new javax.swing.JLabel();
        myTextRed = new MyText();
        jLabel3 = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        jrb_Dec = new javax.swing.JRadioButton();
        jrb_Hex = new javax.swing.JRadioButton();

        myTextBlue.setName("tBlue"); // NOI18N
        myTextBlue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                myTextBlueKeyReleased(evt);
            }
        });

        jLabel1.setText("Синий");
        jLabel1.setName("lBlue"); // NOI18N

        myTextGreen.setName("tGreen"); // NOI18N
        myTextGreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                myTextGreenKeyReleased(evt);
            }
        });

        jLabel2.setText("Зелёный");
        jLabel2.setName("lGreen"); // NOI18N

        myTextRed.setName("tRed"); // NOI18N
        myTextRed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                myTextRedKeyReleased(evt);
            }
        });

        jLabel3.setText("Красный");
        jLabel3.setName("lRed"); // NOI18N

        jPanelColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelColor.setForeground(new java.awt.Color(0, 0, 255));
        jPanelColor.setName("colorPanel"); // NOI18N

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonGroup1.add(jrb_Dec);
        jrb_Dec.setSelected(true);
        jrb_Dec.setText("Dec");
        jrb_Dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_DecActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_Hex);
        jrb_Hex.setText("Hex");
        jrb_Hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_HexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myTextRed, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myTextGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_Dec)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_Hex)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myTextBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myTextRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myTextGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myTextBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_Dec)
                            .addComponent(jrb_Hex)))
                    .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myTextRedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myTextRedKeyReleased
        // red
        //System.out.println("Red = "+myTextRed.getValue()+" Green = " + myTextGreen.getValue() + " Blue = " + myTextBlue.getValue());
        Color color = new Color(myTextRed.getValue(), myTextGreen.getValue(), myTextBlue.getValue());
        jPanelColor.setBackground(color);
    }//GEN-LAST:event_myTextRedKeyReleased

    private void myTextGreenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myTextGreenKeyReleased
        // green
          Color color = new Color(myTextRed.getValue(), myTextGreen.getValue(), myTextBlue.getValue());
        jPanelColor.setBackground(color);
    }//GEN-LAST:event_myTextGreenKeyReleased

    private void myTextBlueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myTextBlueKeyReleased
        // blue
          Color color = new Color(myTextRed.getValue(), myTextGreen.getValue(), myTextBlue.getValue());
        jPanelColor.setBackground(color);
    }//GEN-LAST:event_myTextBlueKeyReleased

    private void jrb_DecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_DecActionPerformed
        // TODO add your handling code here:
        if(jrb_Dec.isSelected()){
            myTextRed.setDec(true);
            myTextBlue.setDec(true);
            myTextGreen.setDec(true);
        }
    }//GEN-LAST:event_jrb_DecActionPerformed

    private void jrb_HexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_HexActionPerformed
        // TODO add your handling code here:
        if(jrb_Hex.isSelected()){
            myTextRed.setDec(false);
            myTextBlue.setDec(false);
            myTextGreen.setDec(false);
        }
    }//GEN-LAST:event_jrb_HexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JRadioButton jrb_Dec;
    private javax.swing.JRadioButton jrb_Hex;
    private MyText myText1;
    private MyText myTextBlue;
    private MyText myTextGreen;
    private MyText myTextRed;
    // End of variables declaration//GEN-END:variables
}
